create table if not exists public.admission_enquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_name text not null, father_name text not null, mother_name text,
  date_of_birth date, gender text, class_name text not null, previous_school text,
  phone text not null, email text, address text
);

create table if not exists public.career_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  applicant_name text not null, gender text, post text not null, phone text not null,
  email text, previous_institution text, experience text, qualification text,
  address text, cv_name text
);

alter table public.admission_enquiries enable row level security;
alter table public.career_applications enable row level security;